stages:
  data_ingestion:
    cmd: python house_price/components/data_ingestion.py
    deps:
      - house_price/components/data_ingestion.py
      - house_price/data_access/mongo_db.py
    outs:
      - artifacts/data_ingestion/feature_store/data.csv

  data_validation:
    cmd: python house_price/components/data_validation.py
    deps:
      - house_price/components/data_validation.py
      - artifacts/data_ingestion/feature_store/data.csv
    outs:
      - artifacts/data_validation/status.json

  data_transformation:
    cmd: python house_price/components/data_transformation.py
    deps:
      - house_price/components/data_transformation.py
      - artifacts/data_validation/status.json
      - artifacts/data_ingestion/feature_store/data.csv
    outs:
      - artifacts/data_transformation/train/train.npy
      - artifacts/data_transformation/test/test.npy