models:
  ridge:
    alpha:
      - 0.1
      - 1
      - 10
      - 100

  random_forest:
    n_estimators:
      - 100
      - 200
      - 300
    max_depth:
      - 10
      - 20 
      - 30
    min_samples_split:
      - 2
      - 5
      - 10
    min_samples_leaf:
      - 1
      - 2
      - 4
  
  xgboost:
    learning_rate:
      - 0.01
      - 0.1 
      - 0.2
    max_depth:
      - 3
      - 5
      - 7
    n_estimators:
      - 100
      - 200
      - 300

